name: env_UncertaintyForecasting
channels:
- conda-forge
- pytorch
dependencies:
  - python==3.6.1
  - seaborn
  - pandas
  - numpy
  - matplotlib
  - cudatoolkit=9.0
  - pygpu==0.7.6
  - pymc3==3.6
  - scikit-learn
  - pytest
  - pytest-cov
  - pip:
    - pyro-ppl
    - prettytable


