name: env_UncertaintyForecasting
channels:
- conda-forge
- pytorch
dependencies:
  - python==3.6.1
  - seaborn==0.9.0
  - pandas==0.24.2
  - numpy==1.13.3
  - matplotlib==2.0.2
  - cudatoolkit==9.0
  - pygpu==0.7.6
  - pymc3==3.6
  - scikit-learn==0.21.2
  - pytest==5.0.1
  - pytest-cov==2.7.1
  - scipy==1.2.1
  - statsmodels==0.9.0
  - dataclasses==0.8
  - pydantic==1.9.2
  - pip:
    - pyro-ppl==0.3.3
    - prettytable==0.7.2
    - git+https://github.com/analytique-bourassa/time_profile_logger.git


